### ISSUE TITLE
Ream for multi thread

### ISSUE THREAD

**Issue by ChinhDV-Android-TL** [betranthanh/android-kotlin-sample-note#1]
NotesRealmManager 
return realm.where(NoteDto::class.java).equalTo("id", id).findFirst()
Sugget
val realm = Realm.getDefaultInstance()
val obj:NoteDto? = realm.where(NoteDto::class.java).equalTo("id", id).findFirst()
val objReturn = realm.copyFromRealm(obj)
realm.close()
return objReturn 

Note: findFirst,findAll return object
copyFromRealm copy to java object

**Comment by betranthanh** [comment]
Thank for your enthusiasm.
Perhaps it's true in your case. But it won't work in this project because we need to use an object what return from find... function to persist to database.

**Comment by ChinhDV-Android-TL** [comment]
Ok i know it dont error for your app. but it  is faied by using realm for your app. Your app is demo for using realm, but it has an error is not good. In my company, some people using realm with singleton, it have 600MB of data. I thing it "should" not "must" change.
